version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: esign
      POSTGRES_USER: esign
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [esign]

  redis:
    image: redis:7
    networks: [esign]

  backend:
    build: ./backend
    env_file: backend/.env
    depends_on: [postgres, redis]
    networks: [esign]

  celery-worker:
    build: ./backend
    env_file: backend/.env
    command: celery -A esign worker --loglevel=info
    depends_on: [backend, redis]
    networks: [esign]

  celery-beat:
    build: ./backend
    env_file: backend/.env
    command: celery -A esign beat --loglevel=info
    depends_on: [backend, redis]
    networks: [esign]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [backend]
    ports:
      - "8080:80"
    networks: [esign]

volumes:
  pgdata:

networks:
  esign:
    name: esign-net
