services:
  - type: web
    name: esign-web
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn esign.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: esign.settings
      - key: CELERY_BROKER_URL
        fromService:
          name: esign-redis
          type: keyvalue
          property: connectionString
      # … autres VARs (POSTGRES_*, DJANGO_SECRET_KEY, etc.)

  - type: worker
    name: esign-celery-worker
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A esign worker --loglevel=INFO --concurrency=2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: esign.settings
      - key: CELERY_BROKER_URL
        fromService:
          name: esign-redis
          type: keyvalue
          property: connectionString

  - type: worker
    name: esign-celery-beat
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A esign beat --loglevel=INFO
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: esign.settings
      - key: CELERY_BROKER_URL
        fromService:
          name: esign-redis
          type: keyvalue
          property: connectionString

  # Render Key Value (Redis®-compatible)
  - type: keyvalue
    name: esign-redis
    region: oregon
    plan: free          # OK pour Key Value
    ipAllowList: []     # requis pour Key Value; [] = accès interne uniquement
    # maxmemoryPolicy: noeviction  # optionnel ; par défaut allkeys-lru
