# Generated by Django 5.2.4 on 2025-07-18 17:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import signature.storages
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(storage=signature.storages.EncryptedFileSystemStorage(), upload_to='signature/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('completed', 'Signé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('hash_original', models.CharField(blank=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('flow_type', models.CharField(choices=[('sequential', 'Séquentiel'), ('parallel', 'Parallèle')], default='sequential', max_length=20)),
                ('reminder_days', models.PositiveIntegerField(default=1)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('jwt_token', models.CharField(blank=True, max_length=512)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnvelopeRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('proof_level', models.CharField(choices=[('guest_simple', 'Guest/simple'), ('account_advanced', 'Compte avancé'), ('qualified', 'Qualifié')], default='guest_simple', max_length=20)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('in_app_notified', models.BooleanField(default=False)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='signature.envelope')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('envelope', 'email')},
            },
        ),
        migrations.CreateModel(
            name='PrintQRCode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_type', models.CharField(choices=[('dynamic', 'Usage unique'), ('permanent', 'Permanent')], max_length=20)),
                ('hmac', models.CharField(editable=False, max_length=64)),
                ('state', models.CharField(default='non_scanned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='signature.envelope')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False)),
                ('signature_data', models.TextField()),
                ('signed_fields', models.JSONField(default=dict)),
                ('signed_file', models.FileField(blank=True, null=True, storage=signature.storages.EncryptedFileSystemStorage(), upload_to='signature/signed/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('certificate_data', models.JSONField(default=dict)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='signature.envelope')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signature.enveloperecipient')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SigningField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('date', 'Date'), ('checkbox', 'Cases'), ('text', 'Texte libre'), ('initial', 'Initiales')], max_length=20)),
                ('page', models.PositiveIntegerField()),
                ('position', models.JSONField()),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='signature.envelope')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='signature.enveloperecipient')),
            ],
        ),
    ]
