# Generated by Django 5.2.4 on 2025-07-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enveloperecipient',
            name='proof_level',
        ),
    ]
