# Generated by Django 5.2.4 on 2025-08-12 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0005_envelopedocument_webhookendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingfield',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='signature.envelopedocument'),
        ),
    ]
