# Generated by Django 4.2.7 on 2025-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0006_signingfield_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='enveloperecipient',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enveloperecipient',
            name='next_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('pending', 'En cours'), ('completed', 'Signé'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='draft', max_length=20),
        ),
    ]
