# Generated by Django 4.2.7 on 2025-08-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0007_enveloperecipient_last_reminder_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookEndpoint',
        ),
    ]
