# Generated by Django 4.2.7 on 2025-08-12 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import signature.storages


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0008_delete_webhookendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('upload', 'Uploaded image'), ('draw', 'Drawn pad'), ('text', 'Typed name')], default='upload', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, storage=signature.storages.EncryptedFileSystemStorage(), upload_to='signature/saved/')),
                ('data_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('page', models.PositiveIntegerField(default=1)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('anchor', models.CharField(blank=True, default='', max_length=200)),
                ('offset_x', models.FloatField(default=0)),
                ('offset_y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchSignJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('self_single', 'Self sign single'), ('bulk_same_spot', 'Bulk same spot'), ('bulk_var_spots', 'Bulk different spots')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('total', models.PositiveIntegerField(default=0)),
                ('done', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_zip', models.FileField(blank=True, null=True, storage=signature.storages.EncryptedFileSystemStorage(), upload_to='signature/batch_zip/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_sign_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchSignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(blank=True, null=True, storage=signature.storages.EncryptedFileSystemStorage(), upload_to='signature/batch_src/')),
                ('placements', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('signed_file', models.FileField(blank=True, null=True, storage=signature.storages.EncryptedFileSystemStorage(), upload_to='signature/batch_signed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signature.envelopedocument')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='signature.batchsignjob')),
            ],
        ),
    ]
