# Generated by Django 5.2.4 on 2025-08-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0009_savedsignature_fieldtemplate_batchsignjob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printqrcode',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='printqrcode',
            name='scanned_at',
        ),
    ]
