# Generated by Django 5.2.4 on 2025-08-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0010_remove_printqrcode_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printqrcode',
            name='state',
        ),
    ]
