# Generated by Django 5.2.4 on 2025-08-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0011_remove_printqrcode_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='printqrcode',
            name='state',
            field=models.CharField(default='non_scanned', max_length=20),
        ),
    ]
