# Generated by Django 5.2.4 on 2025-08-21 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0012_printqrcode_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='doc_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='envelopedocument',
            name='doc_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
