# Generated by Django 5.2.4 on 2025-08-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0013_envelope_doc_uuid_envelopedocument_doc_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='include_qr_code',
            field=models.BooleanField(default=False),
        ),
    ]
