# Generated by Django 5.2.4 on 2025-09-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signature", "0014_envelope_include_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="envelope",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
