# Generated by Django 5.2.4 on 2025-09-17 22:31

import uuid
from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    Envelope = apps.get_model("signature", "Envelope")
    for envelope in Envelope.objects.all():
        envelope.public_id = uuid.uuid4()
        envelope.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("signature", "0015_envelope_cancelled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="envelope",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="envelope",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
